using System;

namespace Orion.Exceptions
{
	/// <summary>UserHandlerException - An exception generated by the user handler.</summary>
	[Serializable]
	public class UserHandlerException : Exception
	{
		/// <summary>Creates a new UserHandlerException object.</summary>
		/// <param name="message">The message for the object.</param>
		/// <returns>A new UserHandlerException object.</returns>
		public UserHandlerException(string message)
			: base(message)
		{
		}

		/// <summary>Creates a new UserHandlerObject with an internal exception.</summary>
		/// <param name="message">The message for the object.</param>
		/// <param name="inner">The inner exception for the object.</param>
		/// <returns>A new UserHandlerException with a defined inner exception.</returns>
		public UserHandlerException(string message, Exception inner)
			: base(message, inner)
		{
		}
	}

	/// <summary>A UserCollisionException object, used when a user already exists when attempting to create a new one.</summary>
	[Serializable]
	public class UserCollisionException : UserHandlerException
	{
		/// <summary>Creates a new UserCollisionException object.</summary>
		/// <param name="name">The name of the user that already exists.</param>
		/// <returns>A UserCollisionException object with the user's name passed in the message.</returns>
		public UserCollisionException(string name)
			: base(String.Format(Strings.UserCollision, name))
		{
		}
	}

	/// <summary>A UserNotFoundException, used when a user does not exist and a query failed as a result of it.</summary>
	[Serializable]
	public class UserNotFoundException : UserHandlerException
	{
		/// <summary>Creates a new UserNotFoundException object, with the user's name in the message.</summary>
		/// <param name="name">The user's name to be pasesd in the message.</param>
		/// <returns>A new UserNotFoundException object with a message containing the user's name that does not exist.</returns>
		public UserNotFoundException(string name)
			: base(String.Format(Strings.UserNotFound, name))
		{
		}
	}
}